---
- name: Backup fortios configurations
  hosts: appc_fortigate_vfwl
  gather_facts: false

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: "Backup running configs to Gitlab repo => {{ config_backup_git_repo_name }}"
      ansible.builtin.import_role:
        name: role-fortios-config-backup
      vars:
        backup: true
        tmp_root_dir: "{{ root_dir }}"
        vendor_dir: "{{ config_backup_git_repo_fortios_dir }}"
        git_repo_name: "{{ config_backup_git_repo_name }}"
        git_repo_url: "{{ config_backup_git_repo_url }}"
        git_repo_branch: "{{ config_backup_git_repo_branch }}"
        git_user: "{{ git_user }}"
        git_user_email: "{{ git_user_email }}"