---
# Fortios config backup.
# Using direct shell ssh to device and extracting configurations.
# Couldn't find a more efficient module in fortios collection
- name: Retrieve configuration from FortiGate
  ansible.builtin.shell: >
    sshpass -p "{{ ansible_password }}" ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }} {{ cmd }} | sed 's/^.*#//g;s/#.*$//g' > {{ tmp_config_store }}
  register: config_output
  failed_when: "'refused' in config_output['stderr']"
  delegate_to: localhost
  ignore_errors: true

- name: Debug results
  ansible.builtin.debug:
    var: config_output
  delegate_to: localhost
