---
# Backup fortios
# - name: Execute backup script
#   ansible.builtin.script: "scripts/fortios_show.sh {{ ansible_user }} {{ ansible_password }}  {{ ansible_host }} {{ tmp_config_store }}"
#   register: config_output
#   failed_when: config_output["failed"] != false
#   delegate_to: localhost

# - name: Debug output
#   ansible.builtin.debug:
#     var: config_output


- name: Retrieve configuration from FortiGate
  ansible.builtin.command: >
    sshpass -p "{{ ansible_password }}" ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }} {{ cmd }}
  register: config_output
  failed_when: config_output["failed"] != false
  delegate_to: localhost


- name: Save the configuration to the temporary config store
  ansible.builtin.copy:
    content: "{{ config_output.stdout }}"
    dest: "{{ tmp_config_store }}"
  delegate_to: localhost